# #499 slice 1 — NIST SP 800-53 Rev 4 ↔ Rev 5 ControlMapping seed.
#
# Loads two ControlMapping records (one per direction) with
# ControlMappingEntry rows derived from the official NIST
# sp800-53r4-to-r5-comparison-workbook.xlsx. The xlsx is vendored at
# lib/data_mappings/sp800-53r4-to-r5-comparison-workbook.xlsx for
# audit traceability; the JSON consumed here is generated by
# `bin/rake nist_rev_mappings:generate`.
#
# Relationship vocabulary per NIST IR 8477:
#   equal       — no significant Rev4→Rev5 change
#   equivalent  — same control id, textual/title/discussion changes
#   superset    — Rev 5 control encompasses a withdrawn Rev 4 control
#                 (i.e., Rev 4 was "incorporated into" the Rev 5 row)
#
# Idempotent on (control_mapping_id, source_control_id, target_control_id).

require "json"

rev5_catalog = ControlCatalog.find_by("name ILIKE ?", "%800-53%5%") ||
               ControlCatalog.find_by("name ILIKE ?", "%Rev 5%") ||
               ControlCatalog.find_by("name ILIKE ?", "%Revision 5%")
rev4_catalog = ControlCatalog.find_by("name ILIKE ?", "%800-53%4%") ||
               ControlCatalog.find_by("name ILIKE ?", "%Rev 4%") ||
               ControlCatalog.find_by("name ILIKE ?", "%Revision 4%")

json_path = Rails.root.join("lib/data_mappings/nist_sp800_53_rev5_to_rev4.json")
skip_reason =
  if !(rev5_catalog && rev4_catalog)
    "Rev 4 or Rev 5 catalog not found (Rev 5: #{rev5_catalog&.name.inspect}, Rev 4: #{rev4_catalog&.name.inspect})"
  elsif !File.exist?(json_path)
    "Mapping JSON not found at #{json_path} — run `bin/rake nist_rev_mappings:generate`"
  end

if skip_reason
  puts "  Skipping NIST Rev4↔Rev5 mapping seed: #{skip_reason}"
else
  data     = JSON.parse(File.read(json_path))
  mappings = data["mappings"] || []

# ── Rev 5 → Rev 4 direction ──────────────────────────────────────────
forward = ControlMapping.find_or_create_by!(
  name: "NIST SP 800-53 Rev 5 → Rev 4"
) do |m|
  m.source_catalog     = rev5_catalog
  m.target_catalog     = rev4_catalog
  m.description        = "NIST SP 800-53 Rev 5 → Rev 4 control mapping derived from the " \
                         "official sp800-53r4-to-r5-comparison-workbook.xlsx (NIST CSRC). " \
                         "Relationship types follow NIST IR 8477."
  m.status             = "complete"
  m.method_type        = "automation"
  m.matching_rationale = "syntactic"
  m.mapping_version    = data["version"].to_s
  m.metadata_extra     = { "source_xlsx" => data["source"], "generated_from" => data["format"] }
end

forward_added = 0
mappings.each_with_index do |entry, idx|
  rec = ControlMappingEntry.find_or_create_by!(
    control_mapping:   forward,
    source_control_id: entry["rev5_id"],
    target_control_id: entry["rev4_id"]
  ) do |e|
    e.relationship       = entry["relationship"]
    e.source_type        = "control"
    e.target_type        = "control"
    e.matching_rationale = "syntactic"
    e.remarks            = entry["rationale"]
    e.row_order          = idx
  end
  forward_added += 1 if rec.previously_new_record?
end

# ── Rev 4 → Rev 5 direction (inverse) ────────────────────────────────
inverse = ControlMapping.find_or_create_by!(
  name: "NIST SP 800-53 Rev 4 → Rev 5"
) do |m|
  m.source_catalog     = rev4_catalog
  m.target_catalog     = rev5_catalog
  m.description        = "NIST SP 800-53 Rev 4 → Rev 5 control mapping (inverse of " \
                         "Rev 5 → Rev 4). Relationship types follow NIST IR 8477; " \
                         "Rev 5 superset edges become Rev 4 subset edges in this direction."
  m.status             = "complete"
  m.method_type        = "automation"
  m.matching_rationale = "syntactic"
  m.mapping_version    = data["version"].to_s
  m.metadata_extra     = { "source_xlsx" => data["source"], "inverse_of" => forward.name }
end

inverse_relationship = ->(rel) {
  case rel
  when "superset" then "subset"
  when "subset"   then "superset"
  else                 rel
  end
}

inverse_added = 0
mappings.each_with_index do |entry, idx|
  rec = ControlMappingEntry.find_or_create_by!(
    control_mapping:   inverse,
    source_control_id: entry["rev4_id"],
    target_control_id: entry["rev5_id"]
  ) do |e|
    e.relationship       = inverse_relationship.call(entry["relationship"])
    e.source_type        = "control"
    e.target_type        = "control"
    e.matching_rationale = "syntactic"
    e.remarks            = entry["rationale"]
    e.row_order          = idx
  end
  inverse_added += 1 if rec.previously_new_record?
end

  puts "  Rev 5 → Rev 4: #{forward.control_mapping_entries.count} entries (+#{forward_added} new)"
  puts "  Rev 4 → Rev 5: #{inverse.control_mapping_entries.count} entries (+#{inverse_added} new)"
end
