# frozen_string_literal: true

require "digest"

# #447 — translation OUT. Database-backed port of
# bin/sparc_findings_to_hdf_amendments.rb: emit an HDF Amendments document
# (schema v3.4.0) from the FindingDispositions for a boundary, for the tenant's CI
# to `hdf amend apply` against their own scan results.
#
# HYBRID (design D5): SPARC hand-emits the JSON — deterministic (stable ordering +
# a content-seeded amendmentId so re-export is byte-identical and cache-pinnable) —
# then runs it through `HdfRunner#amend_verify`, so upstream owns schema + chain +
# expiration validation and any drift surfaces as a failing verify rather than a
# silently-malformed artefact.
#
# Only dispositions whose control_id still appears in the boundary's current
# findings, and which are not expired, are exported — a remediated/absent control
# naturally drops from the amendment, which is exactly what a translation layer
# should do.
#
# Our FindingDisposition.kind values ARE the v3.4.0 override type names, so a kind
# maps straight to `override.type`.
#
# NIST 800-53: CA-7 (continuous monitoring), SI-2 (flaw remediation),
# AU-10 (provenance — appliedBy + signature-seeded id).
class HdfAmendmentExportService
  GENERATOR = { "name" => "sparc/HdfAmendmentExportService", "version" => "1.0.0" }.freeze
  # Fixed namespace (RFC 4122 URL namespace) for deterministic amendmentId v5.
  NAMESPACE_UUID = "6ba7b811-9dad-11d1-80b4-00c04fd430c8"

  def initialize(boundary, runner: HdfRunner.new)
    @boundary = boundary
    @runner = runner
  end

  # @param verify [Boolean] validate the emitted doc via `hdf amend verify`
  # @return [Hash] HDF Amendments document
  def export(verify: true)
    overrides = build_overrides
    doc = {
      "amendmentId" => deterministic_id(overrides),
      "name"        => "SPARC dispositions — #{@boundary.name}",
      "description" => "Generated by SPARC from human-triaged scanner findings for " \
                       "authorization boundary '#{@boundary.name}'. Apply with " \
                       "`hdf amend apply --results <scan.hdf.json> --amendments <this>`.",
      "version"     => "1",
      "generator"   => GENERATOR,
      "labels"      => { "system_id" => (@boundary.slug.presence || @boundary.uuid) },
      "overrides"   => overrides
    }
    @runner.amend_verify(JSON.generate(doc)) if verify
    doc
  end

  private

  def dispositions
    control_ids = @boundary.scanner_findings.pluck(:control_id)
    @boundary.finding_dispositions.active.where(control_id: control_ids).order(:control_id)
  end

  def build_overrides
    dispositions.map do |d|
      override = {
        "type"          => d.kind,
        "requirementId" => d.control_id,
        "status"        => d.hdf_status,
        "reason"        => d.reason,
        "appliedBy"     => identity_for(d.decided_by),
        "appliedAt"     => (d.decided_at || d.created_at).utc.iso8601
      }
      override["expiresAt"] = d.expiration.utc.iso8601 if d.expiration
      override
    end
  end

  def identity_for(who)
    who = who.to_s
    if who.start_with?("@")
      { "type" => "github", "identifier" => who }
    elsif who.include?("@")
      { "type" => "email", "identifier" => who }
    else
      { "type" => "name", "identifier" => who }
    end
  end

  # Same dispositions → same id, so tenants can pin the artefact in a CI cache.
  def deterministic_id(overrides)
    seed = overrides.map do |o|
      [ o["type"], o["requirementId"], o["status"], o["reason"], o["expiresAt"] ].join("|")
    end.join("\n")
    Digest::UUID.uuid_v5(NAMESPACE_UUID, "#{@boundary.uuid}:#{seed}")
  end
end
