# frozen_string_literal: true

# #1147 — does this database actually match the schema the code expects?
#
# ── Why this exists ────────────────────────────────────────────────────────
#
# The #1124 squash replaced 42 schema migrations with a version stamp. That is
# correct for `db:schema:load`, which builds a fresh database FROM `schema.rb`,
# and wrong for `db:migrate`, which never reads `schema.rb` at all. An upgraded
# deployment therefore ends with **zero pending migrations and a schema missing
# columns** — and the only signal was a 500 at runtime, on whichever page
# happened to touch a missing column first.
#
# "No pending migrations" answers the wrong question. This answers the right
# one: is every table, column and index the code expects actually present?
#
# ── How ────────────────────────────────────────────────────────────────────
#
# `schema.rb` is the authority, because it is what a fresh install gets and
# therefore what the code is written against. It is machine-generated and
# stable in shape, so it is parsed rather than executed — executing it against
# a live database is exactly the destructive operation this must never perform.
#
# READ-ONLY BY CONSTRUCTION. It reports; it changes nothing. Repairing arbitrary
# drift automatically would mean inventing DDL for a database nobody has looked
# at, which is how a reporting tool becomes an outage.
class SchemaDriftService
  Drift = Struct.new(:kind, :table, :name, keyword_init: true) do
    def to_s
      case kind
      when :table then "missing table #{table}"
      when :column then "missing column #{table}.#{name}"
      when :index then "missing index #{name} on #{table}"
      end
    end
  end

  # Tables Rails owns and `schema.rb` does not describe the same way.
  IGNORED_TABLES = %w[schema_migrations ar_internal_metadata].freeze

  def initialize(schema_path: Rails.root.join("db/schema.rb"), connection: ActiveRecord::Base.connection)
    @schema_path = schema_path
    @connection = connection
  end

  # [Drift, ...] — empty when the database matches.
  def drift
    expected.flat_map do |table, spec|
      next [ Drift.new(kind: :table, table: table) ] unless live_tables.include?(table)

      missing_columns(table, spec) + missing_indexes(table, spec)
    end
  end

  def clean? = drift.empty?

  # A report an operator can act on, grouped so a 40-column gap reads as one
  # upgrade problem rather than forty unrelated ones.
  def report
    found = drift
    return "schema matches db/schema.rb — #{expected.size} table(s) checked" if found.empty?

    lines = [ "SCHEMA DRIFT: #{found.size} difference(s) against db/schema.rb" ]
    found.group_by(&:table).sort.each do |table, items|
      lines << "  #{table}:"
      items.each { |i| lines << "    - #{i}" }
    end
    lines << ""
    lines << "This database is BEHIND the schema the code expects. `db:migrate` reports"
    lines << "nothing pending because the migrations that would add these were archived"
    lines << "by the #1124 squash; `schema.rb` is only read by a fresh `db:schema:load`."
    lines.join("\n")
  end

  private

  attr_reader :schema_path, :connection

  def live_tables = @live_tables ||= connection.tables

  def missing_columns(table, spec)
    live = connection.columns(table).map(&:name)
    (spec[:columns] - live).map { |c| Drift.new(kind: :column, table: table, name: c) }
  end

  def missing_indexes(table, spec)
    live = connection.indexes(table).map(&:name)
    (spec[:indexes] - live).map { |i| Drift.new(kind: :index, table: table, name: i) }
  end

  # { "table" => { columns: [...], indexes: [...] } }
  #
  # Parsed, not evaluated. `schema.rb` is generated by the schema dumper, so its
  # shape is machine-stable: one `create_table` block per table, one `t.<type>`
  # per column, `t.index` for indexes carrying an explicit name.
  def expected
    @expected ||= begin
      tables = {}
      current = nil
      schema_path.readlines.each do |line|
        if (m = line.match(/^\s*create_table\s+"([^"]+)"/))
          current = m[1]
          tables[current] = { columns: [], indexes: [] } unless IGNORED_TABLES.include?(current)
          current = nil if IGNORED_TABLES.include?(current)
          next
        end
        next if current.nil?

        if line.match?(/^\s*end\s*$/)
          current = nil
        elsif (m = line.match(/^\s*t\.index\s+.*name:\s*"([^"]+)"/))
          tables[current][:indexes] << m[1]
        elsif (m = line.match(/^\s*t\.(?!index|check_constraint)[a-z_]+\s+"([^"]+)"/))
          tables[current][:columns] << m[1]
        end
      end
      tables
    end
  end
end
