require "rails_helper"

RSpec.describe Converter, type: :model do
  describe "validations" do
    subject { Converter.new(name: "Test Converter", converter_type: "cci_to_nist", status: "draft") }

    it { is_expected.to validate_presence_of(:name) }
    it { is_expected.to validate_uniqueness_of(:uuid) }

    it "validates presence of uuid (auto-generated by callback on create)" do
      # The before_validation callback generates uuid on create,
      # so we test the validation exists by checking an update scenario
      converter = Converter.create!(name: "Test", converter_type: "cci_to_nist", status: "draft")
      converter.uuid = nil
      expect(converter).not_to be_valid
      expect(converter.errors[:uuid]).to include("can't be blank")
    end
    it { is_expected.to validate_presence_of(:converter_type) }

    it { is_expected.to validate_inclusion_of(:converter_type).in_array(%w[cci_to_nist cis_to_nist scap_oval_to_nist custom]) }
    it { is_expected.to validate_inclusion_of(:status).in_array(%w[draft complete deprecated processing failed]) }
  end

  describe "associations" do
    it { is_expected.to have_many(:converter_entries).dependent(:destroy) }
  end

  describe "callbacks" do
    it "generates a uuid before validation on create" do
      converter = Converter.new(name: "Auto UUID", converter_type: "cci_to_nist", status: "draft")
      converter.valid?
      expect(converter.uuid).to be_present
    end

    it "does not overwrite an existing uuid" do
      custom_uuid = SecureRandom.uuid
      converter = Converter.new(name: "Custom UUID", converter_type: "cci_to_nist", status: "draft", uuid: custom_uuid)
      converter.valid?
      expect(converter.uuid).to eq(custom_uuid)
    end
  end

  describe "scopes" do
    before do
      Converter.create!(name: "Older", converter_type: "cci_to_nist", status: "complete", updated_at: 2.days.ago)
      Converter.create!(name: "Newer", converter_type: "cci_to_nist", status: "draft", updated_at: 1.day.ago)
      Converter.create!(name: "Newest", converter_type: "cis_to_nist", status: "complete")
    end

    describe ".sorted" do
      it "orders by updated_at descending" do
        names = Converter.sorted.pluck(:name)
        expect(names).to eq([ "Newest", "Newer", "Older" ])
      end
    end

    describe ".published" do
      it "returns only converters with status complete" do
        published = Converter.published.pluck(:name)
        expect(published).to contain_exactly("Older", "Newest")
      end
    end
  end

  describe "#type_label" do
    it "returns the human-readable label for known types" do
      converter = Converter.new(name: "Test", converter_type: "cci_to_nist", status: "draft")
      expect(converter.type_label).to eq("CCI \u2192 NIST")
    end

    it "returns a titleized fallback for unknown types" do
      converter = Converter.new(name: "Test", converter_type: "custom", status: "draft")
      expect(converter.type_label).to eq("Custom")
    end
  end

  describe "#entries_count" do
    it "returns the count of associated converter entries" do
      converter = Converter.create!(name: "Counter", converter_type: "cci_to_nist", status: "draft")
      converter.converter_entries.create!(source_id: "CCI-000001", target_id: "ac-1", relationship: "equal")
      converter.converter_entries.create!(source_id: "CCI-000002", target_id: "ac-2", relationship: "equal")

      expect(converter.entries_count).to eq(2)
    end
  end

  describe "#unique_source_ids" do
    it "returns distinct count of source identifiers" do
      converter = Converter.create!(name: "Sources", converter_type: "cci_to_nist", status: "draft")
      converter.converter_entries.create!(source_id: "CCI-000001", target_id: "ac-1", relationship: "equal")
      converter.converter_entries.create!(source_id: "CCI-000001", target_id: "ac-2", relationship: "equal")
      converter.converter_entries.create!(source_id: "CCI-000002", target_id: "ac-3", relationship: "equal")

      expect(converter.unique_source_ids).to eq(2)
    end
  end

  describe "#unique_target_ids" do
    it "returns distinct count of target identifiers" do
      converter = Converter.create!(name: "Targets", converter_type: "cci_to_nist", status: "draft")
      converter.converter_entries.create!(source_id: "CCI-000001", target_id: "ac-1", relationship: "equal")
      converter.converter_entries.create!(source_id: "CCI-000002", target_id: "ac-1", relationship: "equal")
      converter.converter_entries.create!(source_id: "CCI-000003", target_id: "ac-2", relationship: "equal")

      expect(converter.unique_target_ids).to eq(2)
    end
  end

  describe "#target_families" do
    it "returns sorted unique NIST families from target IDs" do
      converter = Converter.create!(name: "Families", converter_type: "cci_to_nist", status: "draft")
      converter.converter_entries.create!(source_id: "CCI-000001", target_id: "ac-1", relationship: "equal")
      converter.converter_entries.create!(source_id: "CCI-000002", target_id: "ac-2", relationship: "equal")
      converter.converter_entries.create!(source_id: "CCI-000003", target_id: "cm-6", relationship: "equal")
      converter.converter_entries.create!(source_id: "CCI-000004", target_id: "sc-12", relationship: "equal")

      expect(converter.target_families).to eq([ "AC", "CM", "SC" ])
    end
  end

  describe "#coverage_stats" do
    it "returns a comprehensive stats hash" do
      converter = Converter.create!(name: "Stats", converter_type: "cci_to_nist", status: "draft")
      converter.converter_entries.create!(source_id: "CCI-000001", target_id: "ac-1", relationship: "equal")
      converter.converter_entries.create!(source_id: "CCI-000002", target_id: "ac-2", relationship: "equal")
      converter.converter_entries.create!(source_id: "CCI-000003", target_id: "cm-6", relationship: "equal")

      stats = converter.coverage_stats

      expect(stats[:total_entries]).to eq(3)
      expect(stats[:unique_sources]).to eq(3)
      expect(stats[:unique_targets]).to eq(3)
      expect(stats[:families]).to eq([ "AC", "CM" ])
      expect(stats[:family_count]).to eq(2)
    end
  end
end
