# Idempotent seed for NIST SP 800-53 Rev 5 Control Catalog
# Run with: bin/rails db:seed

puts "Seeding NIST SP 800-53 Rev 5 catalog..."

catalog = ControlCatalog.find_or_create_by!(name: "NIST SP 800-53 Rev 5") do |c|
  c.version     = "5.1.1"
  c.source      = "NIST"
  c.description = "Security and Privacy Controls for Information Systems and Organizations. " \
                  "Published by the National Institute of Standards and Technology."
end

NIST_FAMILIES = [
  { code: "AC", name: "Access Control",                              sort_order: 1 },
  { code: "AT", name: "Awareness and Training",                      sort_order: 2 },
  { code: "AU", name: "Audit and Accountability",                    sort_order: 3 },
  { code: "CA", name: "Assessment, Authorization, and Monitoring",   sort_order: 4 },
  { code: "CM", name: "Configuration Management",                    sort_order: 5 },
  { code: "CP", name: "Contingency Planning",                        sort_order: 6 },
  { code: "IA", name: "Identification and Authentication",           sort_order: 7 },
  { code: "IR", name: "Incident Response",                           sort_order: 8 },
  { code: "MA", name: "Maintenance",                                 sort_order: 9 },
  { code: "MP", name: "Media Protection",                            sort_order: 10 },
  { code: "PE", name: "Physical and Environmental Protection",       sort_order: 11 },
  { code: "PL", name: "Planning",                                    sort_order: 12 },
  { code: "PM", name: "Program Management",                          sort_order: 13 },
  { code: "PS", name: "Personnel Security",                          sort_order: 14 },
  { code: "PT", name: "PII Processing and Transparency",            sort_order: 15 },
  { code: "RA", name: "Risk Assessment",                             sort_order: 16 },
  { code: "SA", name: "System and Services Acquisition",            sort_order: 17 },
  { code: "SC", name: "System and Communications Protection",       sort_order: 18 },
  { code: "SI", name: "System and Information Integrity",           sort_order: 19 },
  { code: "SR", name: "Supply Chain Risk Management",               sort_order: 20 },
].freeze

# Base controls data: { family_code => [ [control_num, title, priority, baseline] ] }
# baseline: L=Low, M=Moderate, H=High  (e.g. "L M H" means included in all three)
NIST_CONTROLS = {
  "AC" => [
    [1,  "Policy and Procedures",                                        "P1", "L M H"],
    [2,  "Account Management",                                           "P1", "L M H"],
    [3,  "Access Enforcement",                                           "P1", "L M H"],
    [4,  "Information Flow Enforcement",                                 "P1", "M H"],
    [5,  "Separation of Duties",                                         "P1", "M H"],
    [6,  "Least Privilege",                                              "P1", "M H"],
    [7,  "Unsuccessful Logon Attempts",                                  "P2", "L M H"],
    [8,  "System Use Notification",                                      "P2", "L M H"],
    [9,  "Previous Logon Notification",                                  "P0", ""],
    [10, "Concurrent Session Control",                                   "P2", "M H"],
    [11, "Device Lock",                                                  "P2", "M H"],
    [12, "Session Termination",                                          "P2", "M H"],
    [13, "Withdrawn",                                                    "P0", ""],
    [14, "Permitted Actions Without Identification or Authentication",   "P3", "L M H"],
    [15, "Automated Remote Access Management",                           "P1", "M H"],
    [16, "Security and Privacy Attributes",                              "P2", "M H"],
    [17, "Remote Access",                                                "P1", "L M H"],
    [18, "Wireless Access",                                              "P1", "L M H"],
    [19, "Access Control for Mobile Devices",                           "P1", "M H"],
    [20, "Use of External Systems",                                      "P1", "L M H"],
    [21, "Permitted Actions Without Identification or Authentication",   "P3", "L M H"],
    [22, "Controlled Release",                                           "P1", "M H"],
    [23, "Data Mining Protection",                                       "P0", ""],
    [24, "Access Control Decisions",                                     "P0", ""],
    [25, "Reference Monitor",                                            "P0", ""],
  ],
  "AT" => [
    [1, "Policy and Procedures",                               "P1", "L M H"],
    [2, "Literacy Training and Awareness",                     "P1", "L M H"],
    [3, "Role-Based Training",                                 "P1", "M H"],
    [4, "Training Records",                                    "P3", "M H"],
    [5, "Contacts with Security Groups and Associations",      "P3", ""],
    [6, "Training Feedback",                                   "P2", "M H"],
  ],
  "AU" => [
    [1,  "Policy and Procedures",                          "P1", "L M H"],
    [2,  "Event Logging",                                  "P1", "L M H"],
    [3,  "Content of Audit Records",                       "P1", "L M H"],
    [4,  "Audit Log Storage Capacity",                     "P1", "L M H"],
    [5,  "Response to Audit Logging Process Failures",     "P1", "M H"],
    [6,  "Audit Record Review, Analysis, and Reporting",   "P1", "L M H"],
    [7,  "Audit Record Reduction and Report Generation",   "P2", "M H"],
    [8,  "Time Stamps",                                    "P1", "L M H"],
    [9,  "Protection of Audit Information",                "P1", "L M H"],
    [10, "Audit Record Retention",                         "P3", "L M H"],
    [11, "Audit Record Generation",                        "P1", "L M H"],
    [12, "Audit Record Generation — Protection",           "P1", "H"],
    [13, "Monitoring for Information Disclosure",          "P0", ""],
    [14, "Session Audit",                                  "P0", ""],
    [15, "Non-Repudiation",                                "P0", ""],
    [16, "Protecting Audit Information",                   "P0", ""],
  ],
  "CA" => [
    [1, "Policy and Procedures",                                    "P1", "L M H"],
    [2, "Control Assessments",                                      "P2", "L M H"],
    [3, "Information Exchange",                                     "P1", "L M H"],
    [4, "Withdrawn",                                                "P0", ""],
    [5, "Plan of Action and Milestones",                            "P3", "L M H"],
    [6, "Authorization",                                            "P2", "L M H"],
    [7, "Continuous Monitoring",                                    "P1", "L M H"],
    [8, "Penetration Testing",                                      "P2", "H"],
    [9, "Internal System Connections",                              "P2", "L M H"],
  ],
  "CM" => [
    [1,  "Policy and Procedures",                      "P1", "L M H"],
    [2,  "Baseline Configuration",                     "P1", "L M H"],
    [3,  "Configuration Change Control",               "P1", "M H"],
    [4,  "Security and Privacy Impact Analysis",       "P2", "L M H"],
    [5,  "Access Restrictions for Change",             "P1", "M H"],
    [6,  "Configuration Settings",                     "P1", "L M H"],
    [7,  "Least Functionality",                        "P1", "L M H"],
    [8,  "System Component Inventory",                 "P1", "L M H"],
    [9,  "Configuration Management Plan",              "P1", "M H"],
    [10, "Software Usage Restrictions",                "P2", "L M H"],
    [11, "User-Installed Software",                    "P1", "M H"],
    [12, "Information Location",                       "P1", "L M H"],
    [13, "Data Action Mapping",                        "P0", ""],
    [14, "Signed Components",                          "P0", ""],
  ],
  "CP" => [
    [1,  "Policy and Procedures",                              "P1", "L M H"],
    [2,  "Contingency Plan",                                   "P1", "L M H"],
    [3,  "Contingency Training",                               "P2", "L M H"],
    [4,  "Contingency Plan Testing",                           "P2", "L M H"],
    [5,  "Withdrawn",                                          "P0", ""],
    [6,  "Alternate Storage Site",                             "P1", "M H"],
    [7,  "Alternate Processing Site",                          "P1", "H"],
    [8,  "Telecommunications Services",                        "P1", "M H"],
    [9,  "System Backup",                                      "P1", "L M H"],
    [10, "System Recovery and Reconstitution",                 "P1", "L M H"],
    [11, "Alternate Communications Protocols",                 "P0", ""],
    [12, "Safe Mode",                                          "P0", ""],
    [13, "Data Protection",                                    "P0", ""],
  ],
  "IA" => [
    [1,  "Policy and Procedures",                                        "P1", "L M H"],
    [2,  "Identification and Authentication (Organizational Users)",     "P1", "L M H"],
    [3,  "Device Identification and Authentication",                     "P1", "M H"],
    [4,  "Identifier Management",                                        "P1", "L M H"],
    [5,  "Authenticator Management",                                     "P1", "L M H"],
    [6,  "Authentication Feedback",                                      "P2", "L M H"],
    [7,  "Cryptographic Module Authentication",                          "P1", "L M H"],
    [8,  "Identification and Authentication (Non-Organizational Users)", "P1", "M H"],
    [9,  "Service Identification and Authentication",                    "P1", "H"],
    [10, "Adaptive Authentication",                                      "P0", ""],
    [11, "Re-Authentication",                                            "P2", "M H"],
    [12, "Identity Proofing",                                            "P1", "M H"],
    [13, "Identity Proofing and Re-Authentication",                      "P0", ""],
  ],
  "IR" => [
    [1,  "Policy and Procedures",                  "P1", "L M H"],
    [2,  "Incident Response Training",             "P2", "L M H"],
    [3,  "Incident Response Testing",              "P2", "M H"],
    [4,  "Incident Handling",                      "P1", "L M H"],
    [5,  "Incident Monitoring",                    "P1", "L M H"],
    [6,  "Incident Reporting",                     "P1", "L M H"],
    [7,  "Incident Response Assistance",           "P2", "L M H"],
    [8,  "Incident Response Plan",                 "P1", "L M H"],
    [9,  "Incident Information Sharing",           "P2", "M H"],
    [10, "Supply Chain Coordination",              "P0", ""],
  ],
  "MA" => [
    [1, "Policy and Procedures",                           "P1", "L M H"],
    [2, "Controlled Maintenance",                          "P2", "L M H"],
    [3, "Maintenance Tools",                               "P2", "M H"],
    [4, "Nonlocal Maintenance",                            "P2", "L M H"],
    [5, "Maintenance Personnel",                           "P2", "L M H"],
    [6, "Timely Maintenance",                              "P2", "M H"],
    [7, "Field Maintenance",                               "P0", ""],
  ],
  "MP" => [
    [1, "Policy and Procedures",               "P1", "L M H"],
    [2, "Media Access",                         "P1", "L M H"],
    [3, "Media Marking",                        "P2", "M H"],
    [4, "Media Storage",                        "P1", "M H"],
    [5, "Media Transport",                      "P1", "M H"],
    [6, "Media Sanitization",                   "P1", "L M H"],
    [7, "Media Use",                            "P1", "M H"],
    [8, "Media Downgrading",                    "P0", ""],
  ],
  "PE" => [
    [1,  "Policy and Procedures",                          "P1", "L M H"],
    [2,  "Physical Access Authorizations",                 "P1", "L M H"],
    [3,  "Physical Access Control",                        "P1", "L M H"],
    [4,  "Access Control for Transmission",                "P1", "M H"],
    [5,  "Access Control for Output Devices",              "P2", "M H"],
    [6,  "Monitoring Physical Access",                     "P1", "L M H"],
    [7,  "Visitor Control",                                "P2", "L M H"],
    [8,  "Access Records",                                 "P3", "L M H"],
    [9,  "Power Equipment and Cabling",                    "P1", "H"],
    [10, "Emergency Shutoff",                              "P1", "M H"],
    [11, "Emergency Power",                                "P1", "M H"],
    [12, "Emergency Lighting",                             "P1", "L M H"],
    [13, "Fire Protection",                                "P1", "L M H"],
    [14, "Environmental Controls",                         "P1", "L M H"],
    [15, "Water Damage Protection",                        "P1", "L M H"],
    [16, "Delivery and Removal",                           "P2", "M H"],
    [17, "Alternate Work Site",                            "P2", "M H"],
    [18, "Location of System Components",                  "P2", "H"],
    [19, "Information Leakage",                            "P0", ""],
    [20, "Asset Monitoring and Tracking",                  "P0", ""],
    [21, "Electromagnetic Pulse Protection",               "P0", ""],
    [22, "Component Marking",                              "P0", ""],
    [23, "Facility Location",                              "P0", ""],
  ],
  "PL" => [
    [1,  "Policy and Procedures",                  "P1", "L M H"],
    [2,  "System Security and Privacy Plans",      "P1", "L M H"],
    [3,  "System Security and Privacy Plans — Update", "P2", "L M H"],
    [4,  "Rules of Behavior",                      "P2", "L M H"],
    [5,  "Withdrawn",                              "P0", ""],
    [6,  "Withdrawn",                              "P0", ""],
    [7,  "Concept of Operations",                  "P0", ""],
    [8,  "Security and Privacy Architectures",     "P1", "M H"],
    [9,  "Central Management",                     "P0", ""],
    [10, "Baseline Selection",                     "P0", ""],
    [11, "Baseline Tailoring",                     "P0", ""],
  ],
  "PM" => [
    [1,  "Information Security Program Plan",                          "P1", ""],
    [2,  "Information Security Program Leadership Role",               "P1", ""],
    [3,  "Information Security Resources",                             "P1", ""],
    [4,  "Plan of Action and Milestones Process",                      "P1", ""],
    [5,  "System Inventory",                                           "P1", ""],
    [6,  "Information Security Measures of Performance",               "P1", ""],
    [7,  "Enterprise Architecture",                                    "P1", ""],
    [8,  "Critical Infrastructure Plan",                               "P1", ""],
    [9,  "Risk Management Strategy",                                   "P1", ""],
    [10, "Authorization Process",                                      "P1", ""],
    [11, "Mission and Business Process Definition",                    "P1", ""],
    [12, "Insider Threat Program",                                     "P1", ""],
    [13, "Information Security Workforce",                             "P1", ""],
    [14, "Testing, Training, and Monitoring",                          "P1", ""],
    [15, "Security and Privacy Groups and Associations",               "P2", ""],
    [16, "Threat Awareness Program",                                   "P1", ""],
    [17, "Coordinating with Sanctioning Authority",                    "P0", ""],
    [18, "Privacy Program Plan",                                       "P1", ""],
    [19, "Privacy Program Leadership Role",                            "P1", ""],
    [20, "Dissemination of Privacy Program Information",               "P1", ""],
    [21, "Information Sharing",                                        "P1", ""],
    [22, "Accountability, Audit, and Risk Management",                 "P1", ""],
    [23, "Reporting",                                                  "P1", ""],
    [24, "Data Quality Management",                                    "P1", ""],
    [25, "Data Integrity Board",                                       "P1", ""],
    [26, "Data Management Board",                                      "P0", ""],
    [27, "Event Logging",                                              "P1", ""],
    [28, "System of Records Notice",                                   "P1", ""],
    [29, "Privacy Notice",                                             "P1", ""],
    [30, "Consent",                                                    "P1", ""],
    [31, "Consent Directives",                                         "P0", ""],
    [32, "Computer Matching Requirements",                             "P1", ""],
  ],
  "PS" => [
    [1, "Policy and Procedures",                   "P1", "L M H"],
    [2, "Position Risk Designation",               "P1", "L M H"],
    [3, "Personnel Screening",                     "P1", "L M H"],
    [4, "Personnel Termination",                   "P1", "L M H"],
    [5, "Personnel Transfer",                      "P2", "L M H"],
    [6, "Access Agreements",                       "P3", "L M H"],
    [7, "External Personnel Security",             "P1", "L M H"],
    [8, "Personnel Sanctions",                     "P3", "L M H"],
    [9, "Position Descriptions",                   "P0", ""],
  ],
  "PT" => [
    [1, "Policy and Procedures",                                     "P1", "L M H"],
    [2, "Authority to Process Personally Identifiable Information",  "P1", "L M H"],
    [3, "Personally Identifiable Information Processing Purposes",   "P1", "L M H"],
    [4, "Consent",                                                   "P1", "L M H"],
    [5, "Privacy Notice",                                            "P1", "L M H"],
    [6, "System of Records Notice",                                  "P1", "L M H"],
    [7, "Specific Categories of Personally Identifiable Information","P1", "L M H"],
    [8, "Computer Matching Requirements",                            "P1", "L M H"],
  ],
  "RA" => [
    [1,  "Policy and Procedures",                  "P1", "L M H"],
    [2,  "Security Categorization",                "P1", "L M H"],
    [3,  "Risk Assessment",                        "P1", "L M H"],
    [4,  "Withdrawn",                              "P0", ""],
    [5,  "Vulnerability Monitoring and Scanning",  "P1", "L M H"],
    [6,  "Technical Surveillance Countermeasures", "P0", ""],
    [7,  "Risk Response",                          "P1", "L M H"],
    [8,  "Privacy Impact Assessment",              "P1", "L M H"],
    [9,  "Criticality Analysis",                   "P0", ""],
    [10, "Supply Chain Risk Assessment",           "P1", "M H"],
  ],
  "SA" => [
    [1,  "Policy and Procedures",                                     "P1", "L M H"],
    [2,  "Allocation of Resources",                                   "P1", "L M H"],
    [3,  "System Development Life Cycle",                             "P1", "L M H"],
    [4,  "Acquisition Process",                                       "P1", "L M H"],
    [5,  "System Documentation",                                      "P2", "L M H"],
    [6,  "Withdrawn",                                                 "P0", ""],
    [7,  "Withdrawn",                                                 "P0", ""],
    [8,  "Security and Privacy Engineering Principles",               "P1", "L M H"],
    [9,  "External System Services",                                  "P1", "L M H"],
    [10, "Developer Configuration Management",                        "P1", "M H"],
    [11, "Developer Testing and Evaluation",                          "P1", "M H"],
    [12, "Developer Implementation, Testing, and Evaluation",         "P0", ""],
    [13, "Supply Chain Protection",                                   "P1", "H"],
    [14, "Trustworthiness",                                           "P0", ""],
    [15, "Development Process, Standards, and Tools",                 "P2", "M H"],
    [16, "Developer-Provided Training",                               "P0", ""],
    [17, "Developer Security and Privacy Architecture and Design",    "P1", "H"],
    [18, "Tamper Resistance and Detection",                           "P0", ""],
    [19, "Component Authenticity",                                    "P1", "M H"],
    [20, "Customized Development of Critical Components",             "P0", ""],
    [21, "Developer Screening",                                       "P0", ""],
    [22, "Unsupported System Components",                             "P1", "L M H"],
    [23, "Controlled Use of Interfaces",                              "P0", ""],
  ],
  "SC" => [
    [1,  "Policy and Procedures",                                "P1", "L M H"],
    [2,  "Separation of System and User Functionality",          "P1", "M H"],
    [3,  "Security Function Isolation",                          "P1", "H"],
    [4,  "Information in Shared System Resources",               "P1", "M H"],
    [5,  "Denial-of-Service Protection",                         "P1", "M H"],
    [6,  "Withdrawn",                                            "P0", ""],
    [7,  "Boundary Protection",                                  "P1", "L M H"],
    [8,  "Transmission Confidentiality and Integrity",           "P1", "M H"],
    [9,  "Withdrawn",                                            "P0", ""],
    [10, "Network Disconnect",                                   "P2", "M H"],
    [11, "Withdrawn",                                            "P0", ""],
    [12, "Cryptographic Key Establishment and Management",       "P1", "M H"],
    [13, "Cryptographic Protection",                             "P1", "M H"],
    [14, "Withdrawn",                                            "P0", ""],
    [15, "Withdrawn",                                            "P0", ""],
    [16, "Secure Name/Address Resolution Service",               "P1", "L M H"],
    [17, "Secure Name/Address Resolution Service (Recursive or Caching Resolver)", "P1", "L M H"],
    [18, "Architecture and Provisioning for Name/Address Resolution Service", "P1", "H"],
    [19, "Session Authenticity",                                 "P1", "M H"],
    [20, "Protection of Information at Rest",                    "P1", "M H"],
    [21, "Withdrawn",                                            "P0", ""],
    [22, "Withdrawn",                                            "P0", ""],
    [23, "Withdrawn",                                            "P0", ""],
    [24, "Withdrawn",                                            "P0", ""],
    [25, "Thin Nodes",                                           "P0", ""],
    [26, "Honeypots",                                            "P0", ""],
    [27, "Platform-Independent Applications",                    "P0", ""],
    [28, "Application Partitioning",                             "P0", ""],
    [29, "Heterogeneity",                                        "P0", ""],
    [30, "Concealment and Misdirection",                         "P0", ""],
    [31, "Covert Channel Analysis",                              "P0", ""],
    [32, "Information System Partitioning",                      "P0", ""],
    [33, "Withdrawn",                                            "P0", ""],
    [34, "Non-Modifiable Executable Programs",                   "P0", ""],
    [35, "Honeyclients",                                         "P0", ""],
    [36, "Distributed Processing and Storage",                   "P0", ""],
    [37, "Out-of-Band Channels",                                 "P0", ""],
    [38, "Operations Security",                                  "P0", ""],
    [39, "Process Isolation",                                    "P1", "H"],
    [40, "Withdrawn",                                            "P0", ""],
    [41, "Withdrawn",                                            "P0", ""],
    [42, "Withdrawn",                                            "P0", ""],
    [43, "Usage Restrictions",                                   "P0", ""],
    [44, "Detonation Chambers",                                  "P0", ""],
    [45, "System Time Synchronization",                          "P0", ""],
    [46, "Cross Domain Policy Enforcement",                      "P0", ""],
    [47, "Redundancy",                                           "P0", ""],
    [48, "Sensors",                                              "P0", ""],
    [49, "Hardware-Based Protection",                            "P0", ""],
    [50, "Software-Enforced Separation and Policy Enforcement",  "P0", ""],
    [51, "Physical Machine Separation",                          "P0", ""],
  ],
  "SI" => [
    [1,  "Policy and Procedures",                              "P1", "L M H"],
    [2,  "Flaw Remediation",                                   "P1", "L M H"],
    [3,  "Malicious Code Protection",                          "P1", "L M H"],
    [4,  "System Monitoring",                                  "P1", "L M H"],
    [5,  "Security Alerts, Advisories, and Directives",        "P1", "L M H"],
    [6,  "Security and Privacy Function Verification",         "P1", "H"],
    [7,  "Software, Firmware, and Information Integrity",      "P1", "M H"],
    [8,  "Spam Protection",                                    "P2", "M H"],
    [9,  "Withdrawn",                                          "P0", ""],
    [10, "Information Input Restrictions",                     "P1", "M H"],
    [11, "Information Management and Retention",               "P2", "L M H"],
    [12, "Memory Protection",                                  "P1", "H"],
    [13, "Withdrawn",                                          "P0", ""],
    [14, "Non-Persistence",                                    "P0", ""],
    [15, "Information Output Filtering",                       "P0", ""],
    [16, "Memory Protection",                                  "P0", ""],
    [17, "Fail-Safe Procedures",                               "P0", ""],
    [18, "Operations Security",                                "P0", ""],
    [19, "De-Identification",                                  "P0", ""],
    [20, "Tainting",                                           "P0", ""],
    [21, "Information Disposal",                               "P0", ""],
    [22, "Concealment",                                        "P0", ""],
    [23, "Sensor Capability and Data",                         "P0", ""],
  ],
  "SR" => [
    [1,  "Policy and Procedures",                              "P1", "L M H"],
    [2,  "Supply Chain Risk Management Plan",                  "P1", "M H"],
    [3,  "Supply Chain Controls and Processes",                "P1", "M H"],
    [4,  "Provenance",                                         "P1", "H"],
    [5,  "Acquisition Strategies, Tools, and Methods",         "P1", "M H"],
    [6,  "Supplier Assessments and Reviews",                   "P1", "M H"],
    [7,  "Supply Chain Operations Security",                   "P1", "M H"],
    [8,  "Notification Agreements",                            "P1", "M H"],
    [9,  "Tamper Resistance and Detection",                    "P1", "H"],
    [10, "Inspection of Systems or Components",                "P1", "H"],
    [11, "Component Authenticity",                             "P1", "M H"],
    [12, "Component Disposal",                                 "P1", "M H"],
  ],
}.freeze

total_families = 0
total_controls = 0

NIST_FAMILIES.each do |family_attrs|
  family = ControlFamily.find_or_create_by!(
    control_catalog: catalog,
    code: family_attrs[:code]
  ) do |f|
    f.name       = family_attrs[:name]
    f.sort_order = family_attrs[:sort_order]
  end
  # Update name/sort_order in case it changed
  family.update!(name: family_attrs[:name], sort_order: family_attrs[:sort_order])
  total_families += 1

  controls_for_family = NIST_CONTROLS[family_attrs[:code]] || []
  controls_for_family.each do |num, title, priority, baseline|
    control_id = "#{family_attrs[:code]}-#{num}"
    entry = CatalogControl.find_or_create_by!(
      control_family: family,
      control_id: control_id
    ) do |c|
      c.title           = title
      c.priority        = priority
      c.baseline_impact = baseline.present? ? baseline : nil
    end
    entry.update!(title: title, priority: priority, baseline_impact: baseline.present? ? baseline : nil)
    total_controls += 1
  end
end

puts "  Created/updated #{total_families} control families"
puts "  Created/updated #{total_controls} catalog controls"
puts "Done! NIST SP 800-53 Rev 5 catalog is ready."

# ---------------------------------------------------------------------------
# NIST SP 800-53 Rev 4
# ---------------------------------------------------------------------------
puts "\nSeeding NIST SP 800-53 Rev 4 catalog..."

catalog_r4 = ControlCatalog.find_or_create_by!(name: "NIST SP 800-53 Rev 4") do |c|
  c.version     = "4.0"
  c.source      = "NIST"
  c.description = "Security and Privacy Controls for Federal Information Systems and Organizations. " \
                  "Published by the National Institute of Standards and Technology (superseded by Rev 5)."
end

NIST_R4_FAMILIES = [
  { code: "AC", name: "Access Control",                          sort_order: 1 },
  { code: "AT", name: "Awareness and Training",                  sort_order: 2 },
  { code: "AU", name: "Audit and Accountability",                sort_order: 3 },
  { code: "CA", name: "Security Assessment and Authorization",   sort_order: 4 },
  { code: "CM", name: "Configuration Management",                sort_order: 5 },
  { code: "CP", name: "Contingency Planning",                    sort_order: 6 },
  { code: "IA", name: "Identification and Authentication",       sort_order: 7 },
  { code: "IR", name: "Incident Response",                       sort_order: 8 },
  { code: "MA", name: "Maintenance",                             sort_order: 9 },
  { code: "MP", name: "Media Protection",                        sort_order: 10 },
  { code: "PE", name: "Physical and Environmental Protection",   sort_order: 11 },
  { code: "PL", name: "Planning",                                sort_order: 12 },
  { code: "PM", name: "Program Management",                      sort_order: 13 },
  { code: "PS", name: "Personnel Security",                      sort_order: 14 },
  { code: "RA", name: "Risk Assessment",                         sort_order: 15 },
  { code: "SA", name: "System and Services Acquisition",        sort_order: 16 },
  { code: "SC", name: "System and Communications Protection",   sort_order: 17 },
  { code: "SI", name: "System and Information Integrity",       sort_order: 18 },
].freeze

NIST_R4_CONTROLS = {
  "AC" => [
    [1,  "Access Control Policy and Procedures",                              "P1", "L M H"],
    [2,  "Account Management",                                                "P1", "L M H"],
    [3,  "Access Enforcement",                                                "P1", "L M H"],
    [4,  "Information Flow Enforcement",                                      "P1", "M H"],
    [5,  "Separation of Duties",                                              "P1", "M H"],
    [6,  "Least Privilege",                                                   "P1", "M H"],
    [7,  "Unsuccessful Logon Attempts",                                       "P2", "L M H"],
    [8,  "System Use Notification",                                           "P2", "L M H"],
    [9,  "Previous Logon (Access) Notification",                              "P0", ""],
    [10, "Concurrent Session Control",                                        "P2", "M H"],
    [11, "Session Lock",                                                      "P2", "M H"],
    [12, "Session Termination",                                               "P2", "M H"],
    [13, "Withdrawn",                                                         "P0", ""],
    [14, "Permitted Actions Without Identification or Authentication",        "P3", "L M H"],
    [15, "Withdrawn",                                                         "P0", ""],
    [16, "Security Attributes",                                               "P2", "M H"],
    [17, "Remote Access",                                                     "P1", "L M H"],
    [18, "Wireless Access",                                                   "P1", "L M H"],
    [19, "Access Control for Mobile Devices",                                 "P1", "M H"],
    [20, "Use of External Information Systems",                               "P1", "L M H"],
    [21, "Information Sharing",                                               "P2", "M H"],
    [22, "Publicly Accessible Content",                                       "P3", "L M H"],
    [23, "Data Mining Protection",                                            "P0", ""],
    [24, "Access Control Decisions",                                          "P0", ""],
    [25, "Reference Monitor",                                                 "P0", ""],
  ],
  "AT" => [
    [1, "Security Awareness and Training Policy and Procedures",  "P1", "L M H"],
    [2, "Security Awareness Training",                            "P1", "L M H"],
    [3, "Role-Based Security Training",                           "P1", "M H"],
    [4, "Security Training Records",                              "P3", "M H"],
    [5, "Contacts with Security Groups and Associations",         "P3", ""],
  ],
  "AU" => [
    [1,  "Audit and Accountability Policy and Procedures",    "P1", "L M H"],
    [2,  "Audit Events",                                      "P1", "L M H"],
    [3,  "Content of Audit Records",                          "P1", "L M H"],
    [4,  "Audit Log Storage Capacity",                        "P1", "L M H"],
    [5,  "Response to Audit Processing Failures",             "P1", "M H"],
    [6,  "Audit Review, Analysis, and Reporting",             "P1", "L M H"],
    [7,  "Audit Reduction and Report Generation",             "P2", "M H"],
    [8,  "Time Stamps",                                       "P1", "L M H"],
    [9,  "Protection of Audit Information",                   "P1", "L M H"],
    [10, "Non-Repudiation",                                   "P2", "H"],
    [11, "Audit Record Retention",                            "P3", "L M H"],
    [12, "Audit Generation",                                  "P1", "L M H"],
    [13, "Monitoring for Information Disclosure",             "P0", ""],
    [14, "Session Audit",                                     "P0", ""],
    [15, "Alternate Audit Capability",                        "P0", ""],
    [16, "Cross-Organizational Auditing",                     "P0", ""],
  ],
  "CA" => [
    [1, "Security Assessment and Authorization Policies and Procedures", "P1", "L M H"],
    [2, "Security Assessments",                                          "P2", "L M H"],
    [3, "System Interconnections",                                       "P1", "L M H"],
    [4, "Withdrawn",                                                     "P0", ""],
    [5, "Plan of Action and Milestones",                                 "P3", "L M H"],
    [6, "Security Authorization",                                        "P2", "L M H"],
    [7, "Continuous Monitoring",                                         "P1", "L M H"],
    [8, "Penetration Testing",                                           "P2", "H"],
    [9, "Internal System Connections",                                   "P2", "L M H"],
  ],
  "CM" => [
    [1,  "Configuration Management Policy and Procedures",     "P1", "L M H"],
    [2,  "Baseline Configuration",                             "P1", "L M H"],
    [3,  "Configuration Change Control",                       "P1", "M H"],
    [4,  "Security Impact Analysis",                           "P2", "L M H"],
    [5,  "Access Restrictions for Change",                     "P1", "M H"],
    [6,  "Configuration Settings",                             "P1", "L M H"],
    [7,  "Least Functionality",                                "P1", "L M H"],
    [8,  "Information System Component Inventory",             "P1", "L M H"],
    [9,  "Configuration Management Plan",                      "P1", "M H"],
    [10, "Software Usage Restrictions",                        "P2", "L M H"],
    [11, "User-Installed Software",                            "P1", "M H"],
  ],
  "CP" => [
    [1,  "Contingency Planning Policy and Procedures",         "P1", "L M H"],
    [2,  "Contingency Plan",                                   "P1", "L M H"],
    [3,  "Contingency Training",                               "P2", "L M H"],
    [4,  "Contingency Plan Testing",                           "P2", "L M H"],
    [5,  "Withdrawn",                                          "P0", ""],
    [6,  "Alternate Storage Site",                             "P1", "M H"],
    [7,  "Alternate Processing Site",                          "P1", "H"],
    [8,  "Telecommunications Services",                        "P1", "M H"],
    [9,  "Information System Backup",                          "P1", "L M H"],
    [10, "Information System Recovery and Reconstitution",     "P1", "L M H"],
    [11, "Alternate Communications Protocols",                 "P0", ""],
    [12, "Safe Mode",                                          "P0", ""],
    [13, "Alternative Security Mechanisms",                    "P0", ""],
  ],
  "IA" => [
    [1,  "Identification and Authentication Policy and Procedures",          "P1", "L M H"],
    [2,  "Identification and Authentication (Organizational Users)",          "P1", "L M H"],
    [3,  "Device Identification and Authentication",                          "P1", "M H"],
    [4,  "Identifier Management",                                             "P1", "L M H"],
    [5,  "Authenticator Management",                                          "P1", "L M H"],
    [6,  "Authenticator Feedback",                                            "P2", "L M H"],
    [7,  "Cryptographic Module Authentication",                               "P1", "L M H"],
    [8,  "Identification and Authentication (Non-Organizational Users)",      "P1", "M H"],
    [9,  "Service Identification and Authentication",                         "P1", "H"],
    [10, "Adaptive Identification and Authentication",                        "P0", ""],
    [11, "Re-Authentication",                                                 "P2", "M H"],
  ],
  "IR" => [
    [1,  "Incident Response Policy and Procedures",            "P1", "L M H"],
    [2,  "Incident Response Training",                         "P2", "L M H"],
    [3,  "Incident Response Testing",                          "P2", "M H"],
    [4,  "Incident Handling",                                  "P1", "L M H"],
    [5,  "Incident Monitoring",                                "P1", "L M H"],
    [6,  "Incident Reporting",                                 "P1", "L M H"],
    [7,  "Incident Response Assistance",                       "P2", "L M H"],
    [8,  "Incident Response Plan",                             "P1", "L M H"],
    [9,  "Information Spillage Response",                      "P0", ""],
    [10, "Integrated Information Security Analysis Team",      "P0", ""],
  ],
  "MA" => [
    [1, "System Maintenance Policy and Procedures",    "P1", "L M H"],
    [2, "Controlled Maintenance",                      "P2", "L M H"],
    [3, "Maintenance Tools",                           "P2", "M H"],
    [4, "Nonlocal Maintenance",                        "P2", "L M H"],
    [5, "Maintenance Personnel",                       "P2", "L M H"],
    [6, "Timely Maintenance",                          "P2", "M H"],
  ],
  "MP" => [
    [1, "Media Protection Policy and Procedures",  "P1", "L M H"],
    [2, "Media Access",                             "P1", "L M H"],
    [3, "Media Marking",                            "P2", "M H"],
    [4, "Media Storage",                            "P1", "M H"],
    [5, "Media Transport",                          "P1", "M H"],
    [6, "Media Sanitization",                       "P1", "L M H"],
    [7, "Media Use",                                "P1", "M H"],
    [8, "Media Downgrading",                        "P0", ""],
  ],
  "PE" => [
    [1,  "Physical and Environmental Protection Policy and Procedures", "P1", "L M H"],
    [2,  "Physical Access Authorizations",                              "P1", "L M H"],
    [3,  "Physical Access Control",                                     "P1", "L M H"],
    [4,  "Access Control for Transmission Medium",                      "P1", "M H"],
    [5,  "Access Control for Output Devices",                           "P2", "M H"],
    [6,  "Monitoring Physical Access",                                  "P1", "L M H"],
    [7,  "Withdrawn",                                                   "P0", ""],
    [8,  "Visitor Access Records",                                      "P3", "L M H"],
    [9,  "Power Equipment and Cabling",                                 "P1", "H"],
    [10, "Emergency Shutoff",                                           "P1", "M H"],
    [11, "Emergency Power",                                             "P1", "M H"],
    [12, "Emergency Lighting",                                          "P1", "L M H"],
    [13, "Fire Protection",                                             "P1", "L M H"],
    [14, "Temperature and Humidity Controls",                           "P1", "L M H"],
    [15, "Water Damage Protection",                                     "P1", "L M H"],
    [16, "Delivery and Removal",                                        "P2", "M H"],
    [17, "Alternate Work Site",                                         "P2", "M H"],
    [18, "Location of Information System Components",                   "P2", "H"],
    [19, "Information Leakage",                                         "P0", ""],
    [20, "Asset Monitoring and Tracking",                               "P0", ""],
  ],
  "PL" => [
    [1, "Security Planning Policy and Procedures",         "P1", "L M H"],
    [2, "System Security Plan",                            "P1", "L M H"],
    [3, "Withdrawn",                                       "P0", ""],
    [4, "Rules of Behavior",                               "P2", "L M H"],
    [5, "Withdrawn",                                       "P0", ""],
    [6, "Withdrawn",                                       "P0", ""],
    [7, "Security Concept of Operations",                  "P0", ""],
    [8, "Information Security Architecture",               "P1", "M H"],
    [9, "Central Management",                              "P0", ""],
  ],
  "PM" => [
    [1,  "Information Security Program Plan",                        "P1", ""],
    [2,  "Senior Information Security Officer",                      "P1", ""],
    [3,  "Information Security Resources",                           "P1", ""],
    [4,  "Plan of Action and Milestones Process",                    "P1", ""],
    [5,  "Information System Inventory",                             "P1", ""],
    [6,  "Information Security Measures of Performance",             "P1", ""],
    [7,  "Enterprise Architecture",                                  "P1", ""],
    [8,  "Critical Infrastructure Plan",                             "P1", ""],
    [9,  "Risk Management Strategy",                                 "P1", ""],
    [10, "Security Authorization Process",                           "P1", ""],
    [11, "Mission/Business Process Definition",                      "P1", ""],
    [12, "Insider Threat Program",                                   "P1", ""],
    [13, "Information Security Workforce",                           "P1", ""],
    [14, "Testing, Training, and Monitoring",                        "P1", ""],
    [15, "Contacts with Security Groups and Associations",           "P2", ""],
    [16, "Threat Awareness Program",                                 "P1", ""],
  ],
  "PS" => [
    [1, "Personnel Security Policy and Procedures",    "P1", "L M H"],
    [2, "Position Risk Designation",                   "P1", "L M H"],
    [3, "Personnel Screening",                         "P1", "L M H"],
    [4, "Personnel Termination",                       "P1", "L M H"],
    [5, "Personnel Transfer",                          "P2", "L M H"],
    [6, "Access Agreements",                           "P3", "L M H"],
    [7, "Third-Party Personnel Security",              "P1", "L M H"],
    [8, "Personnel Sanctions",                         "P3", "L M H"],
  ],
  "RA" => [
    [1, "Risk Assessment Policy and Procedures",           "P1", "L M H"],
    [2, "Security Categorization",                         "P1", "L M H"],
    [3, "Risk Assessment",                                 "P1", "L M H"],
    [4, "Withdrawn",                                       "P0", ""],
    [5, "Vulnerability Scanning",                          "P1", "L M H"],
    [6, "Technical Surveillance Countermeasures Survey",   "P0", ""],
  ],
  "SA" => [
    [1,  "System and Services Acquisition Policy and Procedures",          "P1", "L M H"],
    [2,  "Allocation of Resources",                                        "P1", "L M H"],
    [3,  "System Development Life Cycle",                                  "P1", "L M H"],
    [4,  "Acquisition Process",                                            "P1", "L M H"],
    [5,  "Information System Documentation",                               "P2", "L M H"],
    [6,  "Withdrawn",                                                      "P0", ""],
    [7,  "Withdrawn",                                                      "P0", ""],
    [8,  "Security Engineering Principles",                                "P1", "L M H"],
    [9,  "External Information System Services",                           "P1", "L M H"],
    [10, "Developer Configuration Management",                             "P1", "M H"],
    [11, "Developer Security Testing and Evaluation",                      "P1", "M H"],
    [12, "Supply Chain Protection",                                        "P1", "H"],
    [13, "Trustworthiness",                                                "P0", ""],
    [14, "Criticality Analysis",                                           "P0", ""],
    [15, "Development Process, Standards, and Tools",                      "P2", "M H"],
    [16, "Developer-Provided Training",                                    "P0", ""],
    [17, "Developer Security Architecture and Design",                     "P1", "H"],
    [18, "Tamper Resistance and Detection",                                "P0", ""],
    [19, "Component Authenticity",                                         "P1", "M H"],
    [20, "Customized Development of Critical Components",                  "P0", ""],
    [21, "Developer Screening",                                            "P0", ""],
    [22, "Unsupported System Components",                                  "P1", "L M H"],
  ],
  "SC" => [
    [1,  "System and Communications Protection Policy and Procedures",     "P1", "L M H"],
    [2,  "Application Partitioning",                                       "P1", "M H"],
    [3,  "Security Function Isolation",                                    "P1", "H"],
    [4,  "Information in Shared Resources",                                "P1", "M H"],
    [5,  "Denial of Service Protection",                                   "P1", "M H"],
    [6,  "Resource Availability",                                          "P0", ""],
    [7,  "Boundary Protection",                                            "P1", "L M H"],
    [8,  "Transmission Confidentiality and Integrity",                     "P1", "M H"],
    [9,  "Withdrawn",                                                      "P0", ""],
    [10, "Network Disconnect",                                             "P2", "M H"],
    [11, "Trusted Path",                                                   "P0", ""],
    [12, "Cryptographic Key Establishment and Management",                 "P1", "M H"],
    [13, "Cryptographic Protection",                                       "P1", "M H"],
    [14, "Withdrawn",                                                      "P0", ""],
    [15, "Collaborative Computing Devices",                                "P1", "M H"],
    [16, "Transmission of Security Attributes",                            "P0", ""],
    [17, "Public Key Infrastructure Certificates",                         "P1", "M H"],
    [18, "Mobile Code",                                                    "P1", "M H"],
    [19, "Voice Over Internet Protocol",                                   "P1", "M H"],
    [20, "Secure Name/Address Resolution Service (Authoritative Source)",  "P1", "L M H"],
    [21, "Secure Name/Address Resolution Service (Recursive or Caching Resolver)", "P1", "L M H"],
    [22, "Architecture and Provisioning for Name/Address Resolution Service", "P1", "H"],
    [23, "Session Authenticity",                                           "P1", "M H"],
    [24, "Fail in Known State",                                            "P1", "H"],
    [25, "Thin Nodes",                                                     "P0", ""],
    [26, "Honeypots",                                                      "P0", ""],
    [27, "Platform-Independent Applications",                              "P0", ""],
    [28, "Protection of Information at Rest",                              "P1", "M H"],
    [29, "Heterogeneity",                                                  "P0", ""],
    [30, "Concealment and Misdirection",                                   "P0", ""],
    [31, "Covert Channel Analysis",                                        "P0", ""],
    [32, "Information System Partitioning",                                "P0", ""],
    [33, "Withdrawn",                                                      "P0", ""],
    [34, "Non-Modifiable Executable Programs",                             "P0", ""],
    [35, "Honeyclients",                                                   "P0", ""],
    [36, "Distributed Processing and Storage",                             "P0", ""],
    [37, "Out-of-Band Channels",                                           "P0", ""],
    [38, "Operations Security",                                            "P0", ""],
    [39, "Process Isolation",                                              "P1", "H"],
    [40, "Wireless Link Protection",                                       "P0", ""],
    [41, "Port and I/O Device Access",                                     "P0", ""],
    [42, "Sensor Capability and Data",                                     "P0", ""],
    [43, "Usage Restrictions",                                             "P0", ""],
    [44, "Detonation Chambers",                                            "P0", ""],
  ],
  "SI" => [
    [1,  "System and Information Integrity Policy and Procedures",  "P1", "L M H"],
    [2,  "Flaw Remediation",                                        "P1", "L M H"],
    [3,  "Malicious Code Protection",                               "P1", "L M H"],
    [4,  "Information System Monitoring",                           "P1", "L M H"],
    [5,  "Security Alerts, Advisories, and Directives",             "P1", "L M H"],
    [6,  "Security Function Verification",                          "P1", "H"],
    [7,  "Software, Firmware, and Information Integrity",           "P1", "M H"],
    [8,  "Spam Protection",                                         "P2", "M H"],
    [9,  "Withdrawn",                                               "P0", ""],
    [10, "Information Input Validation",                            "P1", "M H"],
    [11, "Error Handling",                                          "P2", "M H"],
    [12, "Information Handling and Retention",                      "P2", "L M H"],
    [13, "Predictable Failure Prevention",                          "P0", ""],
    [14, "Non-Persistence",                                         "P0", ""],
    [15, "Information Output Filtering",                            "P0", ""],
    [16, "Memory Protection",                                       "P1", "H"],
    [17, "Fail-Safe Procedures",                                    "P0", ""],
  ],
}.freeze

r4_families = 0
r4_controls = 0

NIST_R4_FAMILIES.each do |family_attrs|
  family = ControlFamily.find_or_create_by!(
    control_catalog: catalog_r4,
    code: family_attrs[:code]
  ) do |f|
    f.name       = family_attrs[:name]
    f.sort_order = family_attrs[:sort_order]
  end
  family.update!(name: family_attrs[:name], sort_order: family_attrs[:sort_order])
  r4_families += 1

  controls_for_family = NIST_R4_CONTROLS[family_attrs[:code]] || []
  controls_for_family.each do |num, title, priority, baseline|
    control_id = "#{family_attrs[:code]}-#{num}"
    entry = CatalogControl.find_or_create_by!(
      control_family: family,
      control_id: control_id
    ) do |c|
      c.title           = title
      c.priority        = priority
      c.baseline_impact = baseline.present? ? baseline : nil
    end
    entry.update!(title: title, priority: priority, baseline_impact: baseline.present? ? baseline : nil)
    r4_controls += 1
  end
end

puts "  Created/updated #{r4_families} control families"
puts "  Created/updated #{r4_controls} catalog controls"
puts "Done! NIST SP 800-53 Rev 4 catalog is ready."
