#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates the OSCAL XSD element-ordering table consumed by
# OscalJsonToXmlConverter (#827).
#
# WHY THIS EXISTS
#
# OSCAL XML is defined by XSDs in which every assembly is an `xs:sequence` —
# child elements have a MANDATED order. OSCAL JSON has no such requirement, so
# a converter that walks a parsed JSON hash in insertion order produces
# schema-invalid XML wherever the two differ. Fixing that needs a table saying,
# for each element type, what order its children go in.
#
# That table MUST be derived from the schema rather than hand-maintained: it is
# ~112 types deep, and a hand-written copy silently rots the moment NIST ships
# an OSCAL revision. This script derives it from the very XSDs that
# OscalSchemaValidationService validates against, so the ordering used to WRITE
# the XML and the ordering used to CHECK it cannot disagree.
#
# The output is committed rather than generated at boot: it makes the ordering
# reviewable in a diff, costs nothing at runtime, and
# spec/lib/oscal_element_order_spec.rb re-runs this generator and fails if the
# committed table does not match, so the table cannot drift from the XSDs.
#
# USAGE
#   bundle exec ruby scripts/generate_oscal_element_order.rb
#
# Requiring this file does NOT write anything, so the drift spec can require it
# and compare the generated table against the committed one.
#
# WHAT THE TABLE CARRIES
#
# Element order alone is not enough to produce valid OSCAL XML, because three
# further JSON-to-XML decisions are also PER TYPE rather than global:
#
# * `attributes` — which children are XML attributes. `name` is an attribute of
#   <prop> but a child ELEMENT of <party>; `start`/`end` are attributes of
#   <port-range>. A single global attribute list gets all of these wrong.
# * `markup`     — `mixed="true"` types hold prose, whose text must be wrapped
#   in <p>. In JSON the prose sits under the conventional key `prose`.
# * `text`       — `xs:simpleContent` types are attributes PLUS a text value, so
#   the one non-attribute key supplies the element's text rather than a child
#   element (e.g. <document-id scheme="...">identifier</document-id>).
#
# Grouping needs no flag: OSCAL's GROUPED arrays have a real wrapper element in
# the schema (<revisions> wrapping <revision>), so the converter can prefer the
# key as-is when the schema declares it and singularize only when it does not.
#
# ORDERING SEMANTICS
#
# * `xs:sequence`  — children in document order.
# * `xs:group ref` — the referenced group's particles are inlined in position.
# * `xs:choice`    — a document uses ONE branch, but the branches are laid out
#                    in order so that whichever is chosen still sorts correctly
#                    relative to the elements around it.
# * `xs:extension` — the BASE type's particles come first, then the extension's.
# * duplicate names (a name appearing in more than one `xs:choice` branch, e.g.
#   `remarks` after each branch of `timing`) collapse to their LAST position.
#   First-position would rank `remarks` ahead of a later branch's own element
#   and emit them out of order; last-position is correct for every branch.

require "json"
require "nokogiri"
require "pathname"

module OscalElementOrderGenerator
  XS = "http://www.w3.org/2001/XMLSchema"

  ROOT_DIR   = Pathname.new(__dir__).parent
  SCHEMA_DIR = ROOT_DIR.join("lib/oscal_xsd_schemas")
  OUTPUT     = ROOT_DIR.join("lib/oscal_element_order.json")

  # Build-time input only; the generated table is committed, so nothing reads
  # these at runtime. They supply the ONE fact the XSD cannot express: OSCAL
  # JSON sometimes names a group differently from its XML element, e.g.
  # `remediations` is <response> and `related-risks` is <associated-risk>.
  METASCHEMA_DIR = ROOT_DIR.join("spec/fixtures/files/metaschemas")

  class << self
    def generate
      schemas = SCHEMA_DIR.glob("*.xsd").sort
      raise "no XSDs found in #{SCHEMA_DIR}" if schemas.empty?

      @types  = {}   # name => Nokogiri node for xs:complexType
      @groups = {}   # name => Nokogiri node for xs:group
      @roots  = {}   # root element name => type name
      @out    = {}   # type name => { "order" => [...], "children" => {...} }

      schemas.each { |path| collect(path) }
      @types.each_key { |name| flatten_type(name) }

      {
        "_comment" => "GENERATED by scripts/generate_oscal_element_order.rb — do not edit by hand. " \
                      "Regenerate after changing lib/oscal_xsd_schemas/.",
        "_generated_from" => schemas.map { |p| p.basename.to_s },
        "roots" => @roots.sort.to_h,
        "json_aliases" => json_aliases,
        "types" => @out.sort.to_h
      }
    end

    # JSON group name => the OSCAL definition(s) it groups.
    #
    # A `<group-as name="remediations">` inside `<define-assembly
    # name="response">` says the JSON key `remediations` holds <response>
    # elements. The definition name is not ALWAYS the XML element name
    # (`include-controls` groups `select-control-by-id` but the element really
    # is <include-controls>), so the converter treats these as candidates and
    # accepts one only if the parent's schema order actually contains it.
    def json_aliases
      aliases = Hash.new { |h, k| h[k] = [] }

      METASCHEMA_DIR.glob("*.xml").sort.each do |path|
        doc = Nokogiri::XML(path.read) { |cfg| cfg.recover.noent }

        doc.xpath("//*[local-name()='group-as'][@name]").each do |node|
          parent = node.parent
          next if parent.nil?

          # A sibling <use-name> RENAMES the element at this reference site:
          # `<assembly ref="task"><use-name>assessment-task</use-name>` means
          # the JSON key `tasks` holds <assessment-task> here, not <task>.
          use_name = parent.at_xpath("./*[local-name()='use-name']")&.text&.strip
          candidates = [ use_name, parent["name"], parent["ref"] ].compact.reject(&:empty?)
          next if candidates.empty?

          aliases[node["name"]].concat(candidates)
        end
      end

      # Keys sorted for a stable diff, but candidate ORDER is preserved so a
      # use-name rename is preferred over the definition name.
      aliases.transform_values(&:uniq).sort.to_h
    end

    private

    # Index every named complexType, named group and root element declaration.
    # A type defined in more than one XSD must be IDENTICAL in each — OSCAL
    # repeats the shared metadata assemblies across models, and silently
    # picking one of two differing definitions would be a subtle ordering bug.
    def collect(path)
      doc = Nokogiri::XML(path.read)

      doc.xpath("//xs:complexType[@name]", "xs" => XS).each do |node|
        register_unique(@types, node["name"], node, path)
      end

      doc.xpath("//xs:group[@name]", "xs" => XS).each do |node|
        register_unique(@groups, node["name"], node, path)
      end

      doc.xpath("/xs:schema/xs:element[@name][@type]", "xs" => XS).each do |node|
        @roots[node["name"]] = node["type"]
      end
    end

    def register_unique(table, name, node, path)
      existing = table[name]
      if existing && normalize(existing) != normalize(node)
        raise "conflicting definitions of '#{name}' (redefined in #{path.basename})"
      end

      table[name] = node
    end

    # Compare structure, not annotations — OSCAL's human-readable documentation
    # differs harmlessly between models for the same assembly.
    def normalize(node)
      dup = node.dup
      dup.xpath(".//xs:annotation", "xs" => XS).each(&:remove)
      dup.to_xml.gsub(/\s+/, " ").strip
    end

    # Flatten one named type into its ordered direct children. Memoized, so a
    # type shared by several models is only walked once.
    def flatten_type(name)
      return @out[name] if @out.key?(name)

      node = @types[name]
      return nil if node.nil?

      @out[name] = { "order" => [], "children" => {} } # placeholder breaks cycles
      @out[name] = markup_entry_or(node, type_name: name)
    end

    # A markup type (`mixed="true"`) holds prose that may carry inline HTML.
    # Its permitted children are not an assembly the converter ever orders, so
    # record only WHICH markup it is rather than ~150KB of HTML vocabulary
    # nothing reads.
    #
    # OSCAL has two, and they are not interchangeable:
    #   markup-line      — <title>: inline only (a, code, em, ...). Text goes
    #                      straight in; a <p> child is INVALID.
    #   markup-multiline — <description>, <remarks>: block content, where the
    #                      prose MUST be wrapped in <p>.
    # Both are mixed="true", so they are told apart by whether the content
    # model permits <p>.
    def markup_entry_or(node, type_name:)
      kind = markup_kind(node, type_name)
      return build_entry(node, type_name: type_name) unless kind

      entry = { "order" => [], "children" => {}, "markup" => kind }
      attributes = attribute_names(node)
      entry["attributes"] = attributes if attributes.any?
      entry
    end

    # Deliberately does not reuse `walk`: walking registers synthetic types as a
    # side effect, which for markup would re-add the whole HTML vocabulary.
    def permits_paragraphs?(node, seen_groups = [])
      node.element_children.any? do |child|
        next false unless child.namespace&.href == XS

        case child.name
        when "element"
          child["name"] == "p"
        when "extension"
          # The block vocabulary usually lives on the BASE
          # (MarkupMultilineDatatype), not on the extending type.
          base = child["base"]
          (base && @types[base] && permits_paragraphs?(@types[base], seen_groups)) ||
            permits_paragraphs?(child, seen_groups)
        when "sequence", "choice", "all", "complexContent", "simpleContent"
          permits_paragraphs?(child, seen_groups)
        when "group"
          ref = child["ref"]
          ref && !seen_groups.include?(ref) && @groups[ref] &&
            permits_paragraphs?(@groups[ref], seen_groups + [ ref ])
        else
          false
        end
      end
    end

    # Collapse duplicate names to their LAST position, then emit the order, the
    # child=>type map used to descend, and the per-type facts the converter
    # needs to decide attribute-vs-element, markup and text content.
    def build_entry(node, type_name:)
      order = []
      children = {}
      repeats = {}

      walk(node, type_name: type_name, seen_groups: []).each do |element_name, type_ref, unbounded|
        order.delete(element_name)
        order << element_name
        children[element_name] = type_ref
        repeats[element_name] = unbounded
      end

      entry = { "order" => order, "children" => children }

      # A GROUPED array is one whose XML form is a wrapper element holding the
      # repeated child: <revisions><revision/>...</revisions>. Such a wrapper
      # contains exactly one unbounded element and nothing else. Without this
      # the converter cannot tell `revisions` (a wrapper) from `satisfied` (an
      # element that simply repeats), and would emit the latter's items under
      # the wrong name.
      entry["wraps"] = order.first if order.size == 1 && repeats[order.first] && attribute_names(node).empty?
      attributes = attribute_names(node)
      entry["attributes"] = attributes if attributes.any?
      entry["text"] = true if node.at_xpath("./xs:simpleContent", "xs" => XS)
      entry
    end

    # Which markup a type holds, or nil for an ordinary assembly.
    #
    # Markup-ness is usually INHERITED, not declared: <description> is a plain
    # complexType whose entire content is
    # `<xs:extension base="MarkupMultilineDatatype"/>`. And the two datatypes do
    # NOT share a shape — MarkupLineDatatype is mixed inline content, while
    # MarkupMultilineDatatype is ELEMENT-ONLY block content. So `mixed="true"`
    # cannot be the test; resolving to the named datatype is.
    MARKUP_DATATYPES = {
      "MarkupMultilineDatatype" => "multiline",
      "MarkupLineDatatype"      => "line"
    }.freeze

    def markup_kind(node, type_name = nil, seen = [])
      return MARKUP_DATATYPES[type_name] if MARKUP_DATATYPES.key?(type_name)

      # Structural first, so it holds however the type was declared — extending
      # MarkupMultilineDatatype, referencing the block group, or inlining it.
      # No OSCAL assembly has a child element named <p>.
      return "multiline" if permits_paragraphs?(node)

      own_bases(node).each do |base|
        return MARKUP_DATATYPES[base] if MARKUP_DATATYPES.key?(base)
        next if seen.include?(base) || @types[base].nil?

        inherited = markup_kind(@types[base], base, seen + [ base ])
        return inherited if inherited
      end

      # A few assemblies inline the prose vocabulary instead of extending the
      # named datatype. Mixed content is still prose.
      return permits_paragraphs?(node) ? "multiline" : "line" if node["mixed"] == "true"

      nil
    end

    # The bases of THIS type's own content model. Deliberately not `.//` — a
    # descendant search also finds the extensions of nested inline child types,
    # which would make <metadata> inherit markup-ness from its own <title> and
    # emit the whole assembly as prose.
    def own_bases(node)
      node.xpath("./xs:complexContent/xs:extension[@base] | ./xs:simpleContent/xs:extension[@base]",
                 "xs" => XS)
          .map { |ext| ext["base"] }
    end

    # Attributes declared on the type, plus any inherited through an extension
    # base — OSCAL puts shared flags such as `uuid` on the base assembly.
    def attribute_names(node)
      own = node.xpath("./xs:attribute[@name] | " \
                       "./xs:complexContent/xs:extension/xs:attribute[@name] | " \
                       "./xs:simpleContent/xs:extension/xs:attribute[@name]", "xs" => XS)
                .map { |a| a["name"] }

      inherited = own_bases(node).flat_map { |b| @types[b] ? attribute_names(@types[b]) : [] }

      (inherited + own).uniq
    end

    # Walk a particle tree, returning [[element_name, type_name_or_nil], ...]
    # in schema order. Only DIRECT children — an element's own complexType is
    # registered separately and never inlined into its parent's order.
    def walk(node, type_name:, seen_groups:)
      node.element_children.flat_map do |child|
        next [] unless child.namespace&.href == XS

        case child.name
        when "element"    then [ element_particle(child, type_name: type_name, seen_groups: seen_groups) ].compact
        when "sequence", "choice", "all"
          walk(child, type_name: type_name, seen_groups: seen_groups)
        when "group"      then group_particles(child, type_name: type_name, seen_groups: seen_groups)
        when "complexContent", "simpleContent"
          walk(child, type_name: type_name, seen_groups: seen_groups)
        when "extension"  then extension_particles(child, type_name: type_name, seen_groups: seen_groups)
        else []
        end
      end
    end

    # An element contributes itself and, when it declares an inline
    # complexType, a synthesized entry so the converter can descend into it.
    def element_particle(node, type_name:, seen_groups:)
      name = node["name"]
      return nil if name.nil?

      unbounded = node["maxOccurs"] == "unbounded"
      declared = node["type"]
      return [ name, declared, unbounded ] if declared

      inline = node.at_xpath("./xs:complexType", "xs" => XS)
      return [ name, nil, unbounded ] if inline.nil?

      synthetic = "#{type_name}/#{name}"
      unless @out.key?(synthetic)
        @out[synthetic] = { "order" => [], "children" => {} }
        @out[synthetic] = markup_entry_or(inline, type_name: synthetic)
      end

      [ name, synthetic, unbounded ]
    end

    # `seen_groups` guards against a self-referential group definition; OSCAL
    # has none today, but an unguarded resolver would hang rather than fail.
    def group_particles(node, type_name:, seen_groups:)
      ref = node["ref"]
      return [] if ref.nil? || seen_groups.include?(ref)

      target = @groups[ref]
      raise "unresolved xs:group ref='#{ref}'" if target.nil?

      walk(target, type_name: type_name, seen_groups: seen_groups + [ ref ])
    end

    # Inheritance: the base assembly's children precede the extension's own.
    def extension_particles(node, type_name:, seen_groups:)
      base = node["base"]
      inherited = base && @types[base] ? walk(@types[base], type_name: base, seen_groups: seen_groups) : []

      inherited + walk(node, type_name: type_name, seen_groups: seen_groups)
    end
  end
end

if $PROGRAM_NAME == __FILE__
  table = OscalElementOrderGenerator.generate
  OscalElementOrderGenerator::OUTPUT.write("#{JSON.pretty_generate(table)}\n")
  warn "wrote #{OscalElementOrderGenerator::OUTPUT} " \
       "(#{table['types'].size} types, #{table['roots'].size} roots)"
end
