# frozen_string_literal: true

# Represents a parent organization that owns one or more Authorization Boundaries.
# Organizations are never hard-deleted — they are deactivated instead, preserving
# the UUID for audit traceability.
#
# UUID is auto-generated by Postgres gen_random_uuid() and serves as the
# stable audit identifier across the lifecycle of the organization.
class Organization < ApplicationRecord
  include Sluggable
  has_many :organization_memberships, dependent: :destroy
  has_many :users, through: :organization_memberships
  has_many :authorization_boundaries, dependent: :nullify

  # ── Validations ──────────────────────────────────────────────────────────
  validates :name, presence: true,
                   uniqueness: { case_sensitive: false }

  validates :contact_email, format: { with: URI::MailTo::EMAIL_REGEXP },
                            allow_blank: true

  validates :status, inclusion: { in: %w[active inactive] }

  # ── Scopes ───────────────────────────────────────────────────────────────
  scope :active, -> { where(status: "active") }
  scope :inactive, -> { where(status: "inactive") }

  # ── Status helpers ───────────────────────────────────────────────────────

  def active?   = status == "active"
  def inactive? = status == "inactive"

  # Soft-delete: mark as inactive instead of destroying
  def deactivate!
    update!(status: "inactive")
  end

  def reactivate!
    update!(status: "active")
  end
end
